### ISSUE TITLE
请问在egg中怎么用呢？  express demo无法使用

### ISSUE THREAD

**Issue by dpc761218914** [produck/svg-captcha#25]
**Do you want to request a *feature* or report a *bug*?**

**If this is a feature request, what is motivation for changing the behavior?**

**If it is a bug, which version of svg-captcha are you using?**

**What is the current behavior?**

**What is the expected behavior?**

**Step to reproduce the bug or other relevant information**

**Comment by solarhell** [comment]
```javascript
const svgCaptcha = require('svg-captcha');

// 在你的controller中 ctx指上下文
const captcha = svgCaptcha.create();
ctx.session.captcha = captcha.text;
	
ctx.set('Content-Type', 'image/svg+xml')
ctx.status = 200
ctx.body = captcha.data;
```

**Comment by dpc761218914** [comment]
感谢回复，你修改了了ctx.set('Content-Type', 'image/svg+xml')吧？  第一次的方法不行哦，现在可以了，非常感谢~~~ctx.set是设置服务端响应的方式？

**Comment by solarhell** [comment]
就是改改返回的header里的content type

DanielDai <notifications@github.com> 于2018年7月22日周日 下午6:13写道：

**Comment by dpc761218914** [comment]
感谢，明白了~~
