### ISSUE TITLE
support viewBox

### ISSUE THREAD

**Issue by cumt-robin** [produck/svg-captcha#30]
hello, we need to support viewBox property for responsive webpage

plz handle it on pull requests

**Comment by ausir0726** [comment]
Is possible to fix this issue? we need use this SVG in a mobile device.

thanks

**Comment by lichaozhy** [comment]
I am very sorry. I had fixed it in v1.3.12. I've been busy designing v3.x to solve the problems thoroughly but more time need. The new release will solve a series of problems and provide more graceful APIs.  

Keep in touch if you have any questions. Thanks for your support.
