### ISSUE TITLE
Help with Instructions

### ISSUE THREAD

**Issue by CarlaMck77** [produck/svg-captcha#32]
I am new to reactjs, I want to know how to install this in a form

**Comment by ChinaHDJ** [comment]
你可以使用HTTP请求方式获取验证码图片。然后在前端获取到验证码之后。转Blob。然后再使用FileReader。然后获取到Base64的字符串。加到img的src属性里就好了

**Comment by lichaozhy** [comment]
> 
> 
> I am new to reactjs, I want to know how to install this in a form

You should just need **&lt;img src="svgCaptchaImageURL"&gt;** element in your form. It may look like,

```html
<img src="/session/captcha?_t=1554085804760" />
```

Server with Koa,

```js
const svgCaptcha = require('svg-captcha');

app.use(ctx => {
  const captcha = svgCaptcha.create();

  ctx.session.captcha = captcha.text;
  ctx.type = 'image/svg+xml';
  ctx.body = captcha.data;
});
```
