### ISSUE TITLE
This program has been cracked, please fix it

### ISSUE THREAD

**Issue by haua** [produck/svg-captcha#45]
https://github.com/haua/svg-captcha-recognize

**Comment by KawOwl** [comment]
We are working at 3.0, it will include some breaking change.
In 3.0, we can modify the shapes with strategy, for example, snapping them to a virtual grid.
After random modify, it can't get a length to character mapping.
Now for 1.x, we recommend that use multiple fonts.
This issue will not be closed until 3.0 release.
Thanks.

**Comment by haua** [comment]
great, thanks

**Comment by lingsamuel** [comment]
Fixed package published by me: [svg-captcha-fixed](https://www.npmjs.com/package/svg-captcha-fixed)

**Comment by lingsamuel** [comment]
Fixed package published by me: [svg-captcha-fixed](https://www.npmjs.com/package/svg-captcha-fixed)

**Comment by haua** [comment]
> Fixed package published by me: [svg-captcha-fixed](https://www.npmjs.com/package/svg-captcha-fixed)

thanks
