### ISSUE TITLE
node index.js  find the error:"ENOENT: no such file or directory, open 'E:\umore\dailywork\BackSystem\fonts\Comismsh.ttf'"

### ISSUE THREAD

**Issue by whitedxz** [produck/svg-captcha#54]
**Do you want to request a *feature* or report a *bug*?**

**If this is a feature request, what is motivation for changing the behavior?**

**If it is a bug, which version of svg-captcha are you using?**

**What is the current behavior?**

**What is the expected behavior?**

**Step to reproduce the bug or other relevant information**

**Comment by whitedxz** [comment]
const {router} = require('../connect')
const svgCaptcha = require('svg-captcha');


const codeConfig = {
    size: 5,// 验证码长度
    ignoreChars: '0o1i', // 验证码字符中排除 0o1i
    noise: 2, // 干扰线条的数量
    fontSize:42,
    color:true,//开启文字颜色
    background:"#F3F7F2",//背景色
    width:100,
    height: 40
}

router.get('/api/captcha',  (req, res) =>{
       // const captcha = svgCaptcha.createMathExpr(codeConfig);
        const captcha = svgCaptcha.create(codeConfig);
       const codeText=captcha.text.toLowerCase();
       res.send({
           data:{img: captcha.data,codeTxet:codeText},
           code:0,
       });
});


module.exports = {svgCaptchaRouter: router};

**Comment by whitedxz** [comment]
33/5000 
Problem solved,

Create a font file with the same name in the directory and import the font library

**Comment by lichaozhy** [comment]
thx. Any problem else?

**Comment by whitedxz** [comment]
I have a question,
Why does reading font file (.ttf) locally work?
How about reporting this error in production? I'm sure this file is in the directory

**Comment by whitedxz** [comment]
![image](https://user-images.githubusercontent.com/82805837/149919881-f8e486e4-8c25-4f74-9c7c-adf7146d6677.png)

**Comment by whitedxz** [comment]
![1642501820(1)](https://user-images.githubusercontent.com/82805837/149920166-ccfce323-bd43-4ed2-ae91-217238c857b3.png)

**Comment by whitedxz** [comment]
![1642501919(1)](https://user-images.githubusercontent.com/82805837/149920486-b9f85449-20d0-4625-a373-23c994c5ed6d.png)

**Comment by lichaozhy** [comment]
我觉得啊，如果时`node:fs`报告没有文件，那就是真没有这个文件了。这是node标准库的功能。

按照你的开发目录，应该是join到`(__dirname, '../out/fonts/Comismsh.ttf')`吧。但是由于启动和构建方式，我并不能确定你的文件所在路径。

**Comment by whitedxz** [comment]
谢谢大佬 是node版本的问题 感谢了!

**Comment by c2006878** [comment]
> 谢谢大佬 是node版本的问题 感谢了!

应该用什么版本呀
